Tweaked Retired Artist Color
furfsky/furfsky.github.io pull request #28
Opened 2022-02-03 01:57 UTC by DTRW919

If you want I just changed the color of retired artists it just looked strange as the retired/trial artist colors were almost identical. Just reject if needed :)

2022-02-03 03:06 UTC, voxxal requested changes
try `#bbabdb` as grey probably won't contrast well with the background

2022-02-04 16:10 UTC, DTRW919 commented
I think I changed it again, GitHub pull requests are wonky imo

2022-02-12 19:21 UTC, voxxal approved these changes

2022-02-12 19:21 UTC, voxxal commented
lgtm

2022-02-12 19:21 UTC, merged